### PR TITLE
Fix tests to work with rspec-puppet 2.8.0

### PR DESCRIPTION
**Pull request by alexjfisher**
2.7.9 contains https://github.com/rodjek/rspec-puppet/pull/781 and that
appears to have broken our tests.  Fix was pretty simple, but not sure
the rspec-puppet PR was meant to break existing test suites like this.

### CODE REVIEW

**Comment by chrekh** [comment]
It looks right, but doesn't work with the PDK I'm using

```shell
$ rpm -q pdk
pdk-1.18.0.0-1.el8.x86_64

$ pdk test unit
...
Failures:

  1) chrony on archlinux-5-x86_64 chrony::config using defaults 
     Failure/Error: it { is_expected.to contain_file('/etc/chrony.keys').with_content(sensitive("0 xyzzy\n")) }
     
     NoMethodError:
       undefined method `sensitive' for #<RSpec::ExampleGroups::Chrony::OnArchlinux5X8664::ChronyConfig::UsingDefaults:0x00000000074279d8>
     # /opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/rspec-puppet-2.7.8/lib/rspec-puppet/matchers/dynamic_matchers.rb:7:in `method_missing'
     # ./spec/classes/chrony_spec.rb:42:in `block (6 levels) in <top (required)>'
```

**Comment by alexjfisher** [comment]
> It looks right, but doesn't work with the PDK I'm using

`pdk bundle update rspec-puppet` might work?

**Comment by chrekh** [comment]
> > It looks right, but doesn't work with the PDK I'm using
> 
> `pdk bundle update rspec-puppet` might work?

Indeed it did. Thanks!

**Comment by ekohl** [comment]
> `pdk bundle update rspec-puppet` might work?

I'm wondering if we should require rspec-puppet >= 2.7.9 in Gemfile. While it's part of the PDK, that makes it clear we really need that version to work.

**Comment by alexjfisher** [comment]
From slack...

> we’ll work on a PDK release that includes that package
> in the interim, pdk bundle update rspec-puppet might also work

**Comment by alexjfisher** [comment]
rspec-puppet 2.7.9 has been yanked from rubygems

**Review by bastelfreak — APPROVED** [review]
